#ITUACM Machine Learning Study Group Week 1 NumPy Tutorial

NumPy is an open source Python library for using numerical computations as well as manipulating arrays and large dimentional matrices. The NumPy makes the operations faster by 50x compared to standard build-in lists that Python has. <br />
The array type of NumPy is called <b>ndarray</b> which is n-dimensional array that supports different kind of matrix operations such as multiplication and calculates them very fast compared naive implementations.<br />
Although it is a Python library which has written in Python partially, the implementations of operations are implemented in C/C++ to make them faster.<br/>
Why they important? Because NumPy is one of the main libraries that is used in Data Science field. Its speed and easy syntax makes it likable in Data Science community. It is like equivalent to Matlab. It is also Open Source. 

In [4]:
import numpy as np # frequently used with np alias

##N dimensional Array

###Initialization


In [ ]:
#Creating one
one_dim_array = np.array([1, 2, 3, 4])
print("One Dimensional Array: ", one_dim_array)

#Adding Dimensions
two_dim_array = np.array([[1,2], [3,4]])
print("Two Dimensional Array: \n", two_dim_array)

print("\n")

# The dimensions can be printed out using .shape property
print(one_dim_array.shape)
print(two_dim_array.shape)

print("\n")

# The types for all matrices are same
print(type(one_dim_array))
print(type(two_dim_array))

One Dimensional Array:  [1 2 3 4]
Two Dimensional Array: 
 [[1 2]
 [3 4]]


(4,)
(2, 2)


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
#Lists can be converted to NumPy arrays as well
python_list = [1, 2, 3, 4, 5]
print("Python list has type of ", type(python_list))

numpy_array = np.array(python_list)
print("Python list has become: ", type(numpy_array))

Python list has type of  <class 'list'>
Python list has become:  <class 'numpy.ndarray'>


In [ ]:
# Different types of ndarrays 

array_with_zeros = np.zeros((4,4))
print("Array with Zeros: \n", array_with_zeros)

array_with_ones = np.ones((4, 4))
print("\nArray with Ones: \n", array_with_ones)

array_with_specific_number = np.full((4,4), fill_value=420)
print("\nArray filled with 420: \n", array_with_specific_number)

identity = np.eye(5)
print("\nIdentity Matrix: \n", identity)

uniform_random_array = np.random.rand(4,4)
print("\nUniformly randomized array: \n", uniform_random_array)

normal_random_array = np.random.randn(4,4)
print("\nRandomized from normal distribution : \n", normal_random_array)


Array with Zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array with Ones: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array filled with 420: 
 [[420 420 420 420]
 [420 420 420 420]
 [420 420 420 420]
 [420 420 420 420]]

Identity Matrix: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Uniformly randomized array: 
 [[0.86204469 0.54048305 0.31070118 0.6788563 ]
 [0.27762623 0.30926782 0.12060392 0.06682801]
 [0.83016667 0.60562849 0.00697962 0.78081625]
 [0.53467758 0.2027848  0.36999114 0.23585234]]

Randomized from normal distribution : 
 [[ 0.49394026 -0.41534193  0.06878171  0.56223496]
 [-0.58970596 -0.65313702 -0.97497296 -0.13446221]
 [ 0.40618589  0.15425842  1.92247816 -0.00546816]
 [-0.82122236  0.81223366  0.82065327 -0.17716924]]


### Indexing

In [ ]:
random_array = np.random.rand(5,5)

print(random_array)
print("\nThird Row Second Column number is: ", random_array[2][1], random_array[2,1])

# Slicing arrays [start:end], [start:end:step]
print("\nFirst three rows of first column: ", random_array[:3, 0])
print("\nForth Column: ", random_array[:, 3])
print("\nLast Row 3rd, 4th, 5th columns: ", random_array[4, 2:])


#Specified Elements of the Array
print("\nOdd numbered rows', even numbered col's: ", random_array[[0,2], [1,3]])

[[0.02734972 0.26196354 0.27859551 0.17464608 0.09240056]
 [0.38841197 0.74485639 0.702337   0.38718983 0.37664158]
 [0.97191497 0.67159276 0.54221736 0.73768186 0.26207801]
 [0.86719625 0.52354714 0.95036006 0.18669045 0.92289102]
 [0.61734988 0.31258307 0.85594739 0.42670378 0.36133139]]

Third Row Second Column number is:  0.671592762381243 0.671592762381243

First three rows of first column:  [0.02734972 0.38841197 0.97191497]

Forth Column:  [0.17464608 0.38718983 0.73768186 0.18669045 0.42670378]

Last Row 3rd, 4th, 5th columns:  [0.85594739 0.42670378 0.36133139]

 Odd numbered rows', even numbered col's:  [0.26196354 0.73768186]


###Reshaping

In [ ]:
random_array = np.random.rand(6,6)

print(random_array)
#Reshaping array using .reshape()
print("\nNew 9x4 reshaped array: \n", random_array.reshape(9,4))
print("\nNew 2x18 reshaped array: \n", random_array.reshape(2,18))
#Reshape with one dimension unknown
print("\nNew array with one dimension unknown: \n", random_array.reshape(-1, 3)) #(R,G,B), (33, 1) -> (11,3)
print(random_array.shape)
#Resizing with .resize()
print("\nNew array with row dimension unknown: \n", random_array.resize(3, 12))
print(random_array.shape)

[[0.42007928 0.24409884 0.08991243 0.45186134 0.19612368 0.71365663]
 [0.6088135  0.74998667 0.21653761 0.97227793 0.13521129 0.30496505]
 [0.88279783 0.68543458 0.00253398 0.77825529 0.66947451 0.84149301]
 [0.13071282 0.21160246 0.93087934 0.18721519 0.76130633 0.95770037]
 [0.92076717 0.11492872 0.82390475 0.58401771 0.0597642  0.06587952]
 [0.87901096 0.72735482 0.29011357 0.08687693 0.32299664 0.997068  ]]

New 9x4 reshaped array: 
 [[0.42007928 0.24409884 0.08991243 0.45186134]
 [0.19612368 0.71365663 0.6088135  0.74998667]
 [0.21653761 0.97227793 0.13521129 0.30496505]
 [0.88279783 0.68543458 0.00253398 0.77825529]
 [0.66947451 0.84149301 0.13071282 0.21160246]
 [0.93087934 0.18721519 0.76130633 0.95770037]
 [0.92076717 0.11492872 0.82390475 0.58401771]
 [0.0597642  0.06587952 0.87901096 0.72735482]
 [0.29011357 0.08687693 0.32299664 0.997068  ]]

New 2x18 reshaped array: 
 [[0.42007928 0.24409884 0.08991243 0.45186134 0.19612368 0.71365663
  0.6088135  0.74998667 0.21653761 0.9

## Matrix Operations
There are 4 simple operations
- Addition
- Subtraction
- Multiplication
- Division

all of those are calculated element-wise

In [ ]:
temp_arr = np.array([[1,2], [3,4]])

print("Addition: \n", temp_arr + temp_arr)

print("\nSubtract: \n", temp_arr - temp_arr)

print("\nMultiply: \n", temp_arr * temp_arr)

print("\nDivision: \n", temp_arr/temp_arr)

print("\nAdd a scalar: \n", temp_arr + 5) #[[7,8], [7,8]]
print("\nAdd a vector: \n", temp_arr + [7, 8, 9])

In [ ]:
temp_arr = np.random.rand(3,4)
print(temp_arr)

print("\nSum with axis=0: \n", np.sum(temp_arr, axis=0))
print("\nSum with axis=1: \n", np.sum(temp_arr, axis=1))

#Dot Product

print("Dot product of itself: \n", np.dot(temp_arr, temp_arr.T)) # (3,4) x (4,3)

[[0.64670825 0.5821952  0.07903    0.33532609]
 [0.77355895 0.75505943 0.05933346 0.23381911]
 [0.87282555 0.95174777 0.277755   0.6776562 ]]

Sum with axis=0: 
 [2.29309276 2.28900241 0.41611846 1.24680139]

Sum with axis=1: 
 [1.64325954 1.82177095 2.77998453]
Dot product of itself: 
 [[0.87587214 1.02295371 1.36775326]
 [1.02295371 1.22670003 1.56873729]
 [1.36775326 1.56873729 2.20401404]]


##Vectorization

In [ ]:
import time
#vectorization

rand_arr1 = np.random.randn(1000,)
rand_arr2 = np.random.randn(1000,)


#Classic Dot Product
temp = 0
tik = time.process_time()
for i in range(1000):
  temp = temp + float(rand_arr1[i]*rand_arr2[i])
tok = time.process_time()
print("Without vectorization (in milliseconds): "+str((tok-tik)*1000))

tik = time.time()
temp = np.dot(rand_arr1, rand_arr2)
tok = time.time()
print("\nWith vectorization (in milliseconds): " +str((tok-tik)*1000))

print("\n------------------------------------------------------------\n")

#Outer Product
tic = time.process_time()
outer = np.zeros((len(rand_arr1),len(rand_arr2)))
for i in range(len(rand_arr1)):
    for j in range(len(rand_arr2)):
        outer[i,j] = rand_arr1[i]*rand_arr2[j]
toc = time.process_time()
print("\nOuter Product without vectorization (in milliseconds): " + str((toc-tic)*1000))

tic = time.process_time()
outer = np.zeros((len(rand_arr1),len(rand_arr2)))
outer = np.outer(rand_arr1, rand_arr2)
toc = time.process_time()
print("\nOuter Product: with vectorization (in milliseconds): " + str((toc-tic)*1000))

print("\n------------------------------------------------------------\n")

#Elementwise Multiplication
mul = np.zeros((1000,))
tik = time.process_time()
for i in range(1000):
    mul[i] = rand_arr1[i]*rand_arr2[i]
tok = time.process_time()
print("\nElementwise multiplication without vectorization(in milliseconds): "+str((tok-tik)*1000))


tik = time.process_time()
mul = np.multiply(rand_arr1, rand_arr2)
tok = time.process_time()
print("\nElementwise multiplication with vectorization(in milliseconds): "+str((tok-tik)*1000))

Without vectorization (in milliseconds): 0.6976970000001081

With vectorization (in milliseconds): 0.3483295440673828

------------------------------------------------------------


Outer Product without vectorization (in milliseconds): 591.5817419999998

Outer Product: with vectorization (in milliseconds): 9.784122000000117

------------------------------------------------------------


Elementwise multiplication without vectorization(in milliseconds): 0.5925799999997317

Elementwise multiplication with vectorization(in milliseconds): 0.10083800000026955


#Exercises

In [52]:
def CreateAnArray(shape):
  #Given shape as a parameter return, the shape will be 2 dimensional
  # - array of zeros, array of ones, array of uniformly sampled random array

  array_of_zeros = None
  array_of_ones = None
  array_of_uniform_random = None

  return [array_of_zeros, array_of_ones, array_of_uniform_random]

In [53]:
def IndexingArray(arr):
  # Given numpy array as a parameter output required indexed elements
  # Do not worry about the array shape
  # The array provided will 2 dimensional

  # Return 2nd and 4th rows of the given array
  arr1 = None

  # Return 1st, 3rd, and 5th columns of given array
  arr2 = None

  # Return 1st row 2nd column indexed number and 3rd row 4th column indexed number
  arr3 = None

  # Return diagonal of an array 
  #(Hint: Check -> https://numpy.org/doc/stable/reference/generated/numpy.diag.html)
  arr4 = None

  return [arr1, arr2, arr3, arr4]

In [54]:
def ReshapingArray(arr):
  # Given NumPy array as a parameter, reshape the array to required shapes
  # Do not worry about the shape of initial array

  # Flatten the array (convert array to vector (keep the second dimension))
  arr1 = None

  # Change the swap row and column shape with each other, (row, col) => (col, row)
  arr2 = None

  # Increase the dimension of the array by making the last dimension 1
  arr3 = None

  return arr1, arr2, arr3

In [55]:
def MatrixOperations(z):
  # Given NumPy array, implement the given equations 

  # Implement the sigmoid equation
  # Sigmoid Equation: https://en.wikipedia.org/wiki/Sigmoid_function
  sigmoid = None

  # Implement the hyperbolic equations
  # Do not use the build in functions, implement the following:
  # https://en.wikipedia.org/wiki/Hyperbolic_functions#Definitions
  sinh = None
  cosh = None
  tanh = None
  coth = None

  # Implement the ELU function described here:
  # https://en.wikipedia.org/wiki/Rectifier_(neural_networks)#ELU
  # Select the hyper-parameter 'a' as 1
  elu = None

  return sigmoid, sinh, cosh, tanh, coth, elu

# Test
Run this block<br/>
If all 4 parts pass the test, the exercise is complete<br/>
Otherwise check the related part of the code.

In [ ]:
np.random.seed(42) # making sure random arrays output same thing
arrays = CreateAnArray((5,5))
assert arrays[0].all() == np.zeros((5,5)).all(), "Problem with zeros array initialization"
assert arrays[1].all() == np.ones((5,5)).all(), "Problem with ones array initialization"
assert arrays[2].all() == np.random.rand(5,5).all(), "Problem with random array initialization"
print("Matrix Initialization part Passed the tests!")

param_arr = np.random.rand(5,5)
arrays = IndexingArray(param_arr)
assert arrays[0].all() == param_arr[[1, 3], :].all(), "Wrong array indexes for arr1"
assert arrays[1].all() == param_arr[:, [0, 2, 4]].all(), "Wrong array indexes for arr2"
assert arrays[2].all() == param_arr[[0, 2], [1, 3]].all(), "Wrong array indexes for arr3"
assert arrays[3].all() == np.diag(param_arr).all(), "Wrong array indexes for arr4"
print("Indexing Array part Passed the tests!")

param_arr2 = np.random.rand(5,6)
arrays = ReshapingArray(param_arr2)
assert arrays[0].all() == param_arr2.reshape(-1, 1).all(), "Wrong shape for arr1"
assert arrays[1].all() == param_arr2.T.all(), "Wrong shape for arr2"
assert arrays[2].all() == param_arr2.reshape(5,6,1).all(), "Wrong shape for arr3"
print("Reshaping Array part Passed the tests!")

param_arr3 = np.random.rand(1,)
arrays = MatrixOperations(param_arr3)
assert arrays[0] == 1/(1+np.exp(-param_arr3)), "Wrong output for sigmoid, expected" + str(1/(1+np.exp(-param_arr3))) + " got " + str(arrays[0])
assert arrays[1] == np.sinh(param_arr3), "Wrong output for sigmoid, expected" + str(np.sinh(param_arr3)) + " got " + str(arrays[1])
assert arrays[2] == np.cosh(param_arr3), "Wrong output for sigmoid, expected" + str(np.cosh(param_arr3)) + " got " + str(arrays[2])
assert arrays[3] == np.tanh(param_arr3), "Wrong output for sigmoid, expected" + str(np.tanh(param_arr3)) + " got " + str(arrays[3])
assert arrays[4] == 1/np.tanh(param_arr3), "Wrong output for sigmoid, expected" + str(1/np.tanh(param_arr3)) + " got " + str(arrays[4])
assert arrays[5] == [(np.exp(param_arr3)-1) if param_arr3 <= 0 else param_arr3], "Wrong output for sigmoid, expected" + str([(np.exp(param_arr3)-1) if param_arr3 <= 0 else param_arr3]) + " got " + str(arrays[5])
print("Matrix Operations part Passed the tests!")